import React from 'react'
import { useNavigate } from 'react-router-dom'
import { FiArrowLeft } from 'react-icons/fi'

export default function TermsOfService() {
    const navigate = useNavigate()

    return (
        <div style={{ maxWidth: 800, margin: '0 auto', padding: '60px 20px', fontFamily: '"Google Sans", "Inter", sans-serif', color: '#202124' }}>
            <button onClick={() => navigate('/')} style={{ background: 'none', border: 'none', cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 8, color: '#5f6368', fontSize: '1rem', marginBottom: 40, padding: 0 }}>
                <FiArrowLeft /> Back to Home
            </button>
            <h1 style={{ fontSize: '2.5rem', fontWeight: 700, marginBottom: 20 }}>Terms of Service</h1>
            <p style={{ color: '#5f6368', marginBottom: 40 }}>Last updated: December 8, 2025</p>

            <section style={{ marginBottom: 30 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: 15 }}>1. Acceptance of Terms</h2>
                <p style={{ lineHeight: 1.6, color: '#4a4a4a' }}>
                    By accessing and using IdeaBomb ("the Service"), you accept and agree to be bound by the terms and provision of this agreement.
                </p>
            </section>

            <section style={{ marginBottom: 30 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: 15 }}>2. Description of Service</h2>
                <p style={{ lineHeight: 1.6, color: '#4a4a4a' }}>
                    IdeaBomb provides a collaborative whiteboard platform integrated with Gemini AI for brainstorming and project management. We reserve the right to modify or discontinue the Service at any time.
                </p>
            </section>

            <section style={{ marginBottom: 30 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: 15 }}>3. User Conduct</h2>
                <p style={{ lineHeight: 1.6, color: '#4a4a4a' }}>
                    You constitute that you will not use the Service for any illegal purposes or to conduct unlawful activity, including but not limited to fraud, embezzlement, money laundering, or identity theft.
                </p>
            </section>

            <section style={{ marginBottom: 30 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: 15 }}>4. AI Usage</h2>
                <p style={{ lineHeight: 1.6, color: '#4a4a4a' }}>
                    Our Service utilizes Google's Gemini AI models. By using the AI features, you agree to Google's Generative AI terms. Output generated by AI may not always be accurate.
                </p>
            </section>

            <section style={{ marginBottom: 30 }}>
                <h2 style={{ fontSize: '1.5rem', fontWeight: 600, marginBottom: 15 }}>5. Contact</h2>
                <p style={{ lineHeight: 1.6, color: '#4a4a4a' }}>
                    If you have any questions about these Terms, please contact us at arieswu001@gmail.com.
                </p>
            </section>
        </div>
    )
}
